"""Added totalApplications column to campaigns

Revision ID: 589bed972c5f
Revises: 
Create Date: 2024-08-08 18:37:22.766225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589bed972c5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totalApplications', sa.Integer(), nullable=False, default=0))
        
        # Drop constraints with specific names, if they exist.
        # You need to specify constraint names if known; otherwise, remove this line.
        # batch_op.drop_constraint('some_constraint_name', type_='foreignkey')

        # Create foreign key constraint with correct naming
        batch_op.create_foreign_key(
            'fk_campaigns_sponsor_id',  # Constraint name
            'sponsors',  # Referenced table
            ['sponsor_id'],  # Column(s) in 'campaigns' table
            ['id']  # Column(s) in 'sponsors' table
        )

    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_sponsors_name', ['name'])

    # ### end Alembic commands ###